# Generated by Django 4.2 on 2023-04-11 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tryapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Blogpost',
        ),
    ]
