# Generated by Django 4.2 on 2023-04-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryapi', '0002_rename_mymodel_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
